Repository divyasri987/hacktober2022, pull requests merged in 2020-10, with the labels that each got.

#1 Add files via upload
  Bubble Sort Implementation
  Merge Sort.c
  Tik_Tok_tow.c
  Tik_Tok_tow.exe
  binarysearch.c
  bubble sort.c
  helloworld
  helloworld.c
  queue.c
  stack.c
Labels: hacktoberfest-accepted

#2 Add files via upload
  C++/All_tree_(In-Pre-Post order traversal) operation.cpp
  C++/Anagram_checker.cpp
  C++/Array subset of anathor array.cpp
  C++/Array(DS)- Hackerrank
  C++/BSTclass.cpp
  C++/HollowDiamondPattern.cpp
  C++/Hollow_Pyramid.cpp
  C++/In first But Second.cpp
  C++/Longest Consecutive subsequence.cpp
  C++/Longest Sub-array with sum k.cpp
  C++/MohdWarid_SwastikaPattern.cpp
  C++/N-queen(with backtracking).cpp
  C++/NextGreaterElement.cpp
  C++/Nut & colts.cpp
  C++/Painters_Partion_Problem.cpp
  C++/PatternDoubleSidedArrow.cpp
  C++/PermutwithSpaces.cpp
  C++/RabinKarpString.cpp
  C++/Sort element of array by frequency.cpp
  C++/Subarrays with equal 1s and 0s .cpp
  C++/Top view on tree.cpp
  C++/binary_search.cpp
  C++/bucketSort.cpp
  C++/check_prime_number.cpp
  C++/factorial in c++.cpp
  C++/floydWarshals.cpp
  C++/insertionSort.cpp
  C++/knapsack_problem.cpp
  C++/prints number till negative number encountered.cpp
  C++/rat_in_a_maze_game.cpp
Labels: hacktoberfest-accepted

#3 Add files via upload
  Python/Armstrong_Number.py
  Python/Bank_Transaction_System.py
  Python/BubbleSort.py
  Python/Insertion_Sort.py
  Python/Merge_Sort.py
  Python/Python_calc_GUI.py
  Python/Quick Sorting 021.py
  Python/Selection_Sort.py
  Python/anagrams checker.py
  Python/caesar_cipher.py
  Python/calculator.py
  Python/cpp.py
  Python/email_slicer.py
  Python/factorial.py
  Python/hamming.py
  Python/jarvis2.py
  Python/lbp.py
  Python/maze-generator.py
  Python/networks analysis.py
  Python/snake.py
  Python/tic-tac-toe.py
  Python/video_rec.py
  Python/voice.py
Labels: hacktoberfest-accepted

#4 Add files via upload
  Quick Sorting 021.py
Labels: hacktoberfest-accepted

#8 cycle sort
  Cycle sort.c
Labels: hacktoberfest-accepted

#7 beadsort in c
  Bead Sort,c
Labels: good first issue, hacktoberfest-accepted

#6 radix
  radixsort.c
Labels: enhancement, hacktoberfest-accepted

#5 count.c
  count.c
Labels: hacktoberfest-accepted

#9 Created Binary_Search.py
  Python/Binary_Search.py
Labels: hacktoberfest-accepted

#11 sandeep-v1404:Added weather-app made using tkinter
  Python/weather-app-tkinter.py
  Student_Info.c
  tkinter-weather-app.py
Labels: hacktoberfest-accepted

#12 Create Queue.c
  Queue.c
Labels: hacktoberfest-accepted
